In [28]:
# Exercise 0

# H1 TITLE
## H2 TITLE

In [2]:
print("Buy the dip ?")

Buy the dip ?


In [4]:
# Exercise 1

import numpy as np

arr = np.array([10, 3.14, "numpy", {'k': 'v'}, [1, 2], (3, 4), {5, 6}, True], dtype=object)

for i in arr:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [25]:
# Exercise 2

zero = np.zeros(300)
reshaped = zero.reshape(3, 100)
reshaped

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

In [17]:
# Exercise 3

nums = np.arange(1, 101)
odd_nums = nums[::2]
even_nums_rev = nums[1::2][::-1]
nums_copy = nums.copy()
nums_copy[1::3] = 0
nums_copy

array([  1,   0,   3,   4,   0,   6,   7,   0,   9,  10,   0,  12,  13,
         0,  15,  16,   0,  18,  19,   0,  21,  22,   0,  24,  25,   0,
        27,  28,   0,  30,  31,   0,  33,  34,   0,  36,  37,   0,  39,
        40,   0,  42,  43,   0,  45,  46,   0,  48,  49,   0,  51,  52,
         0,  54,  55,   0,  57,  58,   0,  60,  61,   0,  63,  64,   0,
        66,  67,   0,  69,  70,   0,  72,  73,   0,  75,  76,   0,  78,
        79,   0,  81,  82,   0,  84,  85,   0,  87,  88,   0,  90,  91,
         0,  93,  94,   0,  96,  97,   0,  99, 100])

In [18]:
# Exercise 4

np.random.seed(888)
rand1dim = np.random.randn(100)
rand2dim = np.random.randint(1, 11, size=(8, 8))
rand3dim = np.random.randint(1, 18, size=(4, 2, 5,))
rand3dim

array([[[ 5,  2, 13, 16, 15],
        [ 5,  5,  2, 11,  3]],

       [[ 8, 13,  6,  4, 17],
        [ 2,  8,  1, 13, 10]],

       [[12, 17, 17, 12,  1],
        [10,  8, 17,  5, 11]],

       [[ 9, 14,  2, 15, 13],
        [12, 14,  6, 14,  2]]])

In [8]:
# Exercise 5

first = np.arange(1, 51)
second = np.arange(51, 101)
concatenated = np.concatenate((first, second))
reshaped = concatenated.reshape(5, 20)
print(reshaped)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]]


In [9]:
# Exercise 6

matrix_9 = np.ones((9, 9), dtype=np.int8)
print(f'{matrix_9}\n')

matrix_9[1:-1, 1:-1] = 0
matrix_9[2:-2, 2:-2] = 1
matrix_9[3:-3, 3:-3] = 0
matrix_9[4, 4] = 1
print(f'{matrix_9}\n')

array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)
reshaped = array_1.reshape(-1, 1) # Dynamic reshape: (5, 1) in this case
print(reshaped * array_2)  

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [36]:
# Exercise  7

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0., high = 10., size = (10, 2)))
grades[[1, 2, 5, 7], 0] = np.nan
print(f'{grades}\n')

final = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0]).reshape(-1, 1)

concatenated = np.concatenate((grades, final), axis=1)

print(concatenated)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]
