# H1 TITLE
## H2 TITLE

In [2]:
print("Buy the dip ?")

Buy the dip ?


In [3]:
# Exercise 1

import numpy as np
np.set_printoptions(linewidth=np.inf, threshold=1000)

arr = np.array([10, 3.14, "numpy", {'k': 'v'}, [1, 2], (3, 4), {5, 6}, True], dtype=object)

for i in arr:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [4]:
# Exercise 2

zero = np.zeros(300)
print(zero)

reshaped = zero.reshape(3, 100)
print(reshaped)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [5]:
# Exercise 3

nums = np.arange(1, 101)

odd_nums = nums[::2]
print(odd_nums)

even_nums_rev = nums[1::2][::-1]
print(even_nums_rev)

nums_copy = nums.copy()
nums_copy[1::3] = 0
print(nums_copy)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90  91   0  93  94   0  96  97   0  99 100]


In [6]:
# Exercise 4

np.random.seed(888)
np.random.randn(100)

rank2 = np.random.randint(1, 11, size=(8, 8))
print(rank2)

rank3 = np.random.randint(1, 18, (4, 2, 5,))
print(rank3) # No need to precise size= if positional

[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


In [7]:
# Exercise 5

first = np.arange(1, 51)
print(first)

second = np.arange(51, 101)
print(second)

concatenated = np.concatenate((first, second))
print(concatenated)

reshaped = concatenated.reshape(10, 10)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57

In [8]:
# Exercise 6

rank2 = np.ones((9, 9), dtype=np.int8)
print(f'{rank2}\n')

rank2[1:-1, 1:-1] = 0
rank2[2:-2, 2:-2] = 1
rank2[3:-3, 3:-3] = 0
rank2[4, 4] = 1
print(f'{rank2}\n')

array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)
reshaped = array_1.reshape(-1, 1) # Dynamic reshape: (5, 1) in this case
broadcast = reshaped * array_2
print(broadcast)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [9]:
# Exercise  7

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0., high = 10., size = (10, 2)))
grades[[1, 2, 5, 7], 0] = np.nan

final = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0]).reshape(-1, 1)
print(np.concatenate((grades, final), axis=1))

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [14]:
# Exercise 8

data = np.genfromtxt('data/winequality-red.csv', delimiter=';', dtype=np.float32)
print(data)
print(data.nbytes)

data_slice = data[[1, 6, 11]]
print(data_slice)

high_alcohol = np.any(data[:, 10] > 20.)
print(high_alcohol)

alcohol_mean = np.mean(data[:, 10][~np.isnan(data[:, 10])])
print(alcohol_mean)

ph_values = data[:, 8][~np.isnan(data[:, 8])]

min_ph = np.min(ph_values)
print(min_ph)

max_ph = np.max(ph_values)
print(max_ph)

perc25 = format(np.percentile(ph_values, 25), '.2f')
print(perc25)

perc50 = format(np.percentile(ph_values, 50), '.2f')
print(perc50)

perc75 = format(np.percentile(ph_values, 75), '.2f')
print(perc75)

ph_mean = format(np.mean(ph_values), '.2f')
print(ph_mean)

sulfate_col = data[:, 9]
sulfate_val = sulfate_col[~np.isnan(sulfate_col)]
percentile_20 = np.percentile(sulfate_val, 20)

quality_col = data[:, -1]
quality_val = quality_col[~np.isnan(quality_col)]
filtered = quality_col[sulfate_col < percentile_20]
quality_mean = np.mean(filtered)
print(format(quality_mean, '.1f'))

max_quality = np.max(quality_val)
max_quality_mask = quality_col == max_quality
best_quality_data = data[max_quality_mask]
max_mean = np.mean(best_quality_data, axis=0)
print(max_mean)

min_quality = np.min(quality_val)
min_quality_mask = quality_col == min_quality
worst_quality_data = data[min_quality_mask]
min_mean = np.mean(worst_quality_data, axis=0)
print(min_mean)



[[   nan    nan    nan ...    nan    nan    nan]
 [ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
76800
[[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51    0.56    9.4     5.    ]
 [ 7.4     0.66    0.      1.8     0.075  13.     40.      0.9978  3.51    0.56    9.4     5.    ]
 [ 6.7     0.58    0.08    1.8     0.097  15.     65.      0.9959  3.28    0.54    9.2     5.    ]]
False
10.422984
2.74
4.01
3.21
3.31
3.40
3.31
5.2
[ 8.566666    0.4233333   0.39111114  2.5777776   0.06844445 13.277778   33.444443    0.99521226  3.2672222   0.76777774 12.094444    8.        ]
[ 8.359999    0.8845      0.17099999  2.6350002   0.12249999 11.         24.9         0.997464    3.398       0.57000005  9.955       3.        ]


In [ ]:
# Exercise 9

